"""Generate src/scout_logo.h from image/waypost-scout-logo.png.

The logo is 4:3 like the T-Deck's 320x240 screen, so it's scaled to fill it
exactly and stored as plain RGB565 values (R in the top bits) in flash.

Run from the repo root:  python firmware/pocket/tools/make_scout_logo.py
"""

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parents[3]
SRC = ROOT / "image" / "waypost-scout-logo.png"
OUT = ROOT / "firmware" / "pocket" / "src" / "scout_logo.h"
W, H = 320, 240


def rgb565(r: int, g: int, b: int) -> int:
    return ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)


def main() -> None:
    im = Image.open(SRC).convert("RGB").resize((W, H), Image.LANCZOS)
    px = [rgb565(*p) for p in im.getdata()]
    rows = []
    for i in range(0, len(px), 16):
        rows.append("  " + ", ".join(f"0x{v:04x}" for v in px[i : i + 16]) + ",")
    bg = px[0]
    OUT.write_text(
        "// Waypost Scout logo, 320x240 RGB565 (R in the top bits), row-major.\n"
        "// Generated by tools/make_scout_logo.py from image/waypost-scout-logo.png;\n"
        "// do not edit by hand.\n"
        "#pragma once\n"
        "#include <stdint.h>\n\n"
        f"static const uint16_t SCOUT_LOGO_WIDTH = {W};\n"
        f"static const uint16_t SCOUT_LOGO_HEIGHT = {H};\n"
        f"static const uint16_t SCOUT_LOGO_BG = 0x{bg:04x};  // top-left pixel\n"
        "static const uint16_t SCOUT_LOGO[] PROGMEM = {\n" + "\n".join(rows) + "\n};\n"
    )
    print(f"wrote {OUT} ({len(px)} px, bg 0x{bg:04x})")


if __name__ == "__main__":
    main()
