"""Noticeboard protocol constants."""

OP_NOTICE_LIST = "NOTICE_LIST"
OP_NOTICE_GET = "NOTICE_GET"
OP_NOTICE_CREATE = "NOTICE_CREATE"
OP_NOTICE_EXPIRE = "NOTICE_EXPIRE"
OP_NOTICE_ACK = "NOTICE_ACK"

MAX_BODY = 8000
MAX_TITLE = 160
