"""Postbox / mail protocol operations."""

OP_MAIL_STATUS = "MAIL_STATUS"
OP_MAIL_LIST = "MAIL_LIST"
OP_MAIL_GET = "MAIL_GET"
OP_MAIL_SEND = "MAIL_SEND"
OP_MAIL_REPLY = "MAIL_REPLY"
OP_MAIL_MARK = "MAIL_MARK"
OP_MAIL_NOTIFY = "MAIL_NOTIFY"
OP_MAIL_FLUSH = "MAIL_FLUSH"

FOLDER_INBOX = "INBOX"
FOLDER_SENT = "SENT"
FOLDER_OUTBOX = "OUTBOX"
FOLDER_DRAFTS = "DRAFTS"

DEFAULT_MAIL_DOMAIN = "waypost"
