"""Gzips the Outpost's Wi-Fi page (web/) into src/web_assets.h so it's
served straight from flash — the file system holds the Outpost's identity
and claim, and uploading a file-system image would wipe them.

    python tools/make_web_assets.py     (from firmware/outpost)
"""

import gzip
from pathlib import Path

HERE = Path(__file__).resolve().parent.parent
ASSETS = [  # (served path, file under web/, content type)
    ("/msg", "msg.html", "text/html; charset=utf-8"),
    ("/js/msg.js", "msg.js", "text/javascript"),
    ("/js/wpcrypto.js", "wpcrypto.js", "text/javascript"),
    ("/js/nacl.js", "vendor/nacl-fast.min.js", "text/javascript"),
    ("/js/scrypt.js", "vendor/scrypt.js", "text/javascript"),
]

out = ["// Generated by tools/make_web_assets.py from web/ — do not edit by hand.",
       "#pragma once", "#include <cstddef>", "#include <cstdint>", "#include <pgmspace.h>", "",
       "struct WebAsset {", "  const char* path;", "  const char* type;", "  const uint8_t* data;",
       "  size_t len;  // gzipped", "};", ""]
total = 0
for i, (path, name, ctype) in enumerate(ASSETS):
    data = gzip.compress((HERE / "web" / name).read_bytes(), compresslevel=9, mtime=0)
    total += len(data)
    rows = [", ".join(f"0x{b:02x}" for b in data[j:j + 20]) for j in range(0, len(data), 20)]
    out.append(f"static const uint8_t WEB_ASSET_{i}[] PROGMEM = {{")
    out += [f"  {r}," for r in rows]
    out.append("};")
out.append("")
out.append("static const WebAsset WEB_ASSETS[] = {")
for i, (path, name, ctype) in enumerate(ASSETS):
    out.append(f'  {{"{path}", "{ctype}", WEB_ASSET_{i}, sizeof(WEB_ASSET_{i})}},')
out.append("};")
out.append(f"static const size_t WEB_ASSET_COUNT = {len(ASSETS)};")
(HERE / "src" / "web_assets.h").write_text("\n".join(out) + "\n")
print(f"src/web_assets.h: {len(ASSETS)} files, {total} bytes gzipped")
